# CHAPTER 3

# Section 1
## Playing with PyTorch tensors

In [1]:
import torch

data = torch.ones(3)
data

tensor([1., 1., 1.])

In [2]:
data[0], data[1]

(tensor(1.), tensor(1.))

In [3]:
float(data[0]), float(data[1])

(1.0, 1.0)

In [4]:
data[1] = 4 # mutable
data

tensor([1., 4., 1.])

In [5]:
a = torch.tensor([4, 5, 6, 7])
a

tensor([4, 5, 6, 7])

In [6]:
a.dtype

torch.int64

In [7]:
float(a[2])

6.0

In [8]:
p = torch.tensor([[4, 2], [4, 5.6], [1.3, 13]], dtype=torch.float64)
p

tensor([[ 4.0000,  2.0000],
        [ 4.0000,  5.6000],
        [ 1.3000, 13.0000]], dtype=torch.float64)

In [9]:
p.shape

torch.Size([3, 2])

In [10]:
p[0]

tensor([4., 2.], dtype=torch.float64)

In [11]:
p[0, 0], p[0, 1]

(tensor(4., dtype=torch.float64), tensor(2., dtype=torch.float64))

In [12]:
p[:, 0] # all rows, first column

tensor([4.0000, 4.0000, 1.3000], dtype=torch.float64)

In [13]:
p[None].shape

torch.Size([1, 3, 2])

In [14]:
# example image
img = torch.rand(3, 28, 28) * 255 # channels x rows x columns
img

tensor([[[150.2530,  84.3327, 169.2895,  ..., 207.5652,   9.4286,  45.8134],
         [  6.7548, 206.8150, 101.8646,  ..., 101.9380, 209.2569, 159.7717],
         [175.1369, 192.9887, 180.0000,  ...,  26.3084,  89.9467,  91.7967],
         ...,
         [250.5806, 113.1538, 119.3091,  ..., 131.4570, 126.2439, 182.9778],
         [  3.3541, 211.3625, 122.2391,  ..., 109.5555, 240.4821, 199.2412],
         [  3.4502, 235.0827,  50.1306,  ...,  79.5683, 129.5877, 195.0822]],

        [[209.0943,  40.8407, 149.6735,  ..., 109.9375,  29.0814, 150.5322],
         [203.3565,  58.5944, 123.7024,  ..., 196.9795, 234.5605, 121.7710],
         [246.1909, 151.3152, 143.8917,  ...,  26.7317,  55.9566, 221.6695],
         ...,
         [206.6034, 170.4484, 173.6024,  ...,  46.8081,  56.3252, 101.7402],
         [196.5774,  61.0541, 168.7843,  ..., 241.9117, 100.2323, 127.9265],
         [104.2544,  98.3051, 172.6106,  ...,  49.2955,  48.9284, 194.4702]],

        [[ 55.5011, 146.2720,   5.8271,  ...

In [15]:
w = torch.tensor([0.2126, 0.7152, 0.0722]) 
batch = torch.rand(2, 3, 28, 28) # 2 is the number of examples
w.shape

torch.Size([3])

In [16]:
img.mean(-3).shape, batch.mean(-3).shape

(torch.Size([28, 28]), torch.Size([2, 28, 28]))

In [17]:
w_un = w.unsqueeze(-1).unsqueeze(-1)
w_un.shape

torch.Size([3, 1, 1])

In [18]:
img_weights = w_un * img
batch_weights = w_un * batch

img_weights.shape, batch_weights.shape

(torch.Size([3, 28, 28]), torch.Size([2, 3, 28, 28]))

In [19]:
%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt

In [20]:
img_gray = img_weights.sum(-3)
batch_gray = batch_weights.sum(-3)
img_gray.shape, batch_gray.shape

(torch.Size([28, 28]), torch.Size([2, 28, 28]))

In [23]:
# trying to plot the images
print(img.shape, batch.shape)

torch.Size([3, 28, 28]) torch.Size([2, 3, 28, 28])


In [21]:
# different dtypes in pytorch

torch.int8, torch.int16, torch.int32, torch.int64
torch.float, torch.float16, torch.float32, torch.float64
torch.bool

torch.bool

In [22]:
# TO CHANGE THE DTYPE TWO METHODS ARE THERE
print(p.dtype)
print(p.int().dtype)
print(p.to(torch.int64).dtype)

torch.float64
torch.int32
torch.int64
