# CHAPTER 3

# Section 1
## Playing with PyTorch tensors

In [1]:
import torch

data = torch.ones(3)
data

tensor([1., 1., 1.])

In [2]:
data[0], data[1]

(tensor(1.), tensor(1.))

In [6]:
float(data[0]), float(data[1])

(1.0, 1.0)

In [7]:
data[1] = 4 # mutable
data

tensor([1., 4., 1.])

In [29]:
a = torch.tensor([4, 5, 6, 7])
a

tensor([4, 5, 6, 7])

In [30]:
a.dtype

torch.int64

In [31]:
float(a[2])

6.0

In [36]:
p = torch.tensor([[4, 2], [4, 5.6], [1.3, 13]])
p

tensor([[ 4.0000,  2.0000],
        [ 4.0000,  5.6000],
        [ 1.3000, 13.0000]])

In [37]:
p.shape

torch.Size([3, 2])

In [40]:
p[0]

tensor([4., 2.])

In [42]:
p[0, 0], p[0, 1]

(tensor(4.), tensor(2.))

In [49]:
p[:, 0] # all rows, first column

tensor([4.0000, 4.0000, 1.3000])

In [51]:
p[None].shape

torch.Size([1, 3, 2])

In [71]:
# example image
img = torch.rand(3, 28, 28) * 255 # channels x rows x columns
img

tensor([[[2.6082e+01, 2.0362e+02, 8.9376e+01,  ..., 1.6312e+02,
          2.4112e+02, 1.7508e+02],
         [1.9464e+02, 1.8717e+02, 1.9525e+02,  ..., 2.5957e+01,
          1.1157e+02, 1.4985e+02],
         [2.2557e+02, 5.0284e+01, 8.9906e+01,  ..., 1.0140e+02,
          1.6019e+02, 7.7235e+01],
         ...,
         [1.5787e+02, 1.5522e+02, 3.2340e+01,  ..., 7.7242e+01,
          1.2891e+02, 1.4741e+02],
         [5.4691e+01, 9.1341e+01, 1.7802e+02,  ..., 2.5185e+02,
          1.7679e+02, 2.3859e+02],
         [2.0709e+02, 2.3805e+02, 5.5195e+01,  ..., 8.0122e+01,
          4.8276e-01, 5.6730e+01]],

        [[1.3352e+02, 6.7626e+01, 1.9827e+02,  ..., 1.2484e+02,
          6.7956e+00, 5.8851e+01],
         [1.6823e+02, 1.0759e+02, 1.3795e+02,  ..., 1.8265e+02,
          1.2693e+02, 1.3713e-01],
         [1.8773e+02, 1.6842e+02, 1.2600e+02,  ..., 5.2019e+01,
          2.2085e+02, 5.7551e+01],
         ...,
         [9.0552e+01, 2.0259e+02, 4.2185e+01,  ..., 2.3851e+02,
          8.444

In [73]:
w = torch.tensor([0.2126, 0.7152, 0.0722]) 
batch = torch.rand(2, 3, 28, 28) # 2 is the number of examples

In [77]:
img.mean(-3).shape, batch.mean(-3).shape

(torch.Size([28, 28]), torch.Size([2, 28, 28]))