# CHAPTER 3

# Section 1
## Playing with PyTorch tensors

In [1]:
import torch

data = torch.ones(3)
data

tensor([1., 1., 1.])

In [2]:
data[0], data[1]

(tensor(1.), tensor(1.))

In [3]:
float(data[0]), float(data[1])

(1.0, 1.0)

In [4]:
data[1] = 4 # mutable
data

tensor([1., 4., 1.])

In [5]:
a = torch.tensor([4, 5, 6, 7])
a

tensor([4, 5, 6, 7])

In [6]:
a.dtype

torch.int64

In [7]:
float(a[2])

6.0

In [41]:
p = torch.tensor([[4, 2], [4, 5.6], [1.3, 13]], dtype=torch.float64)
p

tensor([[ 4.0000,  2.0000],
        [ 4.0000,  5.6000],
        [ 1.3000, 13.0000]], dtype=torch.float64)

In [9]:
p.shape

torch.Size([3, 2])

In [10]:
p[0]

tensor([4., 2.])

In [11]:
p[0, 0], p[0, 1]

(tensor(4.), tensor(2.))

In [12]:
p[:, 0] # all rows, first column

tensor([4.0000, 4.0000, 1.3000])

In [13]:
p[None].shape

torch.Size([1, 3, 2])

In [14]:
# example image
img = torch.rand(3, 28, 28) * 255 # channels x rows x columns
img

tensor([[[182.3879, 145.3529, 195.3352,  ..., 171.6509, 236.7178, 142.0307],
         [174.5888,  27.0570, 160.1863,  ..., 102.0893,  16.5979, 130.0339],
         [240.9228, 207.0613, 238.9397,  ..., 134.4095, 235.8065, 160.1673],
         ...,
         [ 84.0016,   1.3655, 149.8852,  ..., 210.5795,  59.1937, 254.4714],
         [ 65.4600,  70.6929, 238.7603,  ..., 123.4414,  88.7924,  39.2632],
         [  9.4948, 182.8233, 253.8066,  ...,  72.0883,  86.7520,  59.2587]],

        [[140.0709,   2.2248,  81.1570,  ...,  13.2627, 102.4947,  24.9196],
         [ 46.5436,  62.4156, 129.0915,  ..., 182.0855, 193.1869,  56.4675],
         [195.1279, 164.7365,  17.1165,  ...,  81.4968, 245.7850, 171.8754],
         ...,
         [  4.9265,  42.8052, 105.5150,  ...,  23.7668, 201.6915, 176.4352],
         [203.4769,  90.7972,  47.5656,  ..., 194.3567, 230.2426, 163.6752],
         [ 32.8484, 181.4916,  17.9884,  ..., 134.4347,   9.8782, 226.5210]],

        [[ 56.7857,  63.1181, 178.4857,  ...

In [16]:
w = torch.tensor([0.2126, 0.7152, 0.0722]) 
batch = torch.rand(2, 3, 28, 28) # 2 is the number of examples
w.shape

torch.Size([3])

In [17]:
img.mean(-3).shape, batch.mean(-3).shape

(torch.Size([28, 28]), torch.Size([2, 28, 28]))

In [26]:
w_un = w.unsqueeze(-1).unsqueeze(-1)
w_un.shape

torch.Size([3, 1, 1])

In [27]:
img_weights = w_un * img
batch_weights = w_un * batch

img_weights.shape, batch_weights.shape

(torch.Size([3, 28, 28]), torch.Size([2, 3, 28, 28]))

In [28]:
%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt

In [32]:
img_gray = img_weights.sum(-3)
batch_gray = batch_weights.sum(-3)
img_gray.shape, batch_gray.shape

(torch.Size([28, 28]), torch.Size([2, 28, 28]))

In [42]:
# different dtypes in pytorch

torch.int8, torch.int16, torch.int32, torch.int64
torch.float, torch.float16, torch.float32, torch.float64
torch.bool

torch.bool

In [47]:
# TO CHANGE THE DTYPE TWO METHODS ARE THERE
print(p.dtype)
print(p.int().dtype)
print(p.to(torch.int64).dtype)

torch.float64
torch.int32
torch.int64
